# Generated by Django 4.2.16 on 2024-09-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_discount_order_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
    ]
